package br.mil.eb.decex.sisaluno.enumerated;

public enum EspecialidadeArma {
	//Especialidade ou arma do curso que o militar está realizando.
		
	PERIODO_BASICO("Período Básico"),
	ARTILHARIA("Artilharia"),
	AVIACAO("Aviação"),
	CAVALARIA("Cavalaria"),
	COMUNICACOES("Comunicações"),
	ENGENHARIA("Engenharia"),
	INFANTARIA("Infantaria"),
	INTENDENCIA("Intendência"),
	MATERIAL_BELICO("Material Bélico"),
	MUSICA("Música"),
	SAUDE("Saúde"),
	TOPOGRAFIA("Topografia"),
	FARMACIA("Farmácia"),
	MEDICO("Médico"),
	ODONTO("Odontologia"),
	DENTISTA("Dentista"),
	QCO("Quadro Complementar de Oficiais"),
	CFGO("Curso de Formação e Graduação de Oficiais"),
	CPOR("Centro de Preparação de Oficiais da Reserva"),
	CTBMF("Cirurgia e Traumatologia Buco Maxilo Facial"),
	DRO("Dentística Restauradora Odontológica"),
	ENDO("Endodontia"),
	OOF("Ortodontia e Ortopedia Facial"),
	PERIO("Periodontia"),
	ACUPUNTURA("Acupuntura"),
	ALERGIA_IMUNOLOGIA("Alergia e imunologia"),
	ANESTESIOLOGIA("Anestesiologia"),
	ANGIOLOGIA("Angiologia"),
	CARDIOLOGIA("Cardiologia"),
	CIRURGIA_CARDIOVASCULAR("Cirurgia cardiovascular"),
	CIRURGIA_MAO("Cirurgia da mão"),
	CIRURGIA_CABECA_PESCOCO("Cirurgia de cabeça e pescoço"),
	CIRURGIA_APARELHO_DIGESTIVO("Cirurgia do aparelho digestivo"),
	CIRURGIA_GERAL("Cirurgia geral"),
	CIRURGIA_ONCOLOGICA("Cirurgia oncológica"),
	CIRURGIA_PEDIATRICA("Cirurgia pediátrica"),
	CIRURGIA_PLASTICA("Cirurgia plástica"),
	CIRURGIA_TORACICA("Cirurgia torácica"),
	CIRURGIA_VASCULAR("Cirurgia vascular"),
	CLÍNICA_MEDICA("Clínica médica"),
	COLOPROCTOLOGIA("Coloproctologia"),
	DERMATOLOGIA("Dermatologia"),
	ENDOCRINOLOGIA_METABOLOGIA("Endocrinologia e metabologia"),
	ENDOSCOPIA("Endoscopia"),
	GASTROENTEROLOGIA("Gastroenterologia"),
	GENETICA_MEDICA("Genética médica"),
	GERIATRIA("Geriatria"),
	GINECOLOGIA_OBSTETRICIA("Ginecologia e obstetrícia"),
	HEMATOLOGIA_HEMOTERAPIA("Hematologia e hemoterapia"), 
	HOMEOPATIA("Homeopatia"),
	INFECTOLOGIA("Infectologia"),
	MASTOLOGIA("Mastologia"),
	MEDICINA_EMERGENCIA("Medicina de emergência"),
	MEDICINA_FAMILIA_COMUNIDADE("Medicina de família e comunidade"),
	MEDICINA_DO_TRABALHO("Medicina do trabalho"),
	MEDICINA_TRAFEGO("Medicina de tráfego"),
	MEDICINA_ESPORTIVA("Medicina esportiva"),
	MEDICINA_FISICA_REABILITACAO("Medicina física e reabilitação"),
	MEDICINA_INTENSIVA("Medicina intensiva"),
	MEDICINA_LEGAL_PERICIA_MEDICA("Medicina legal e perícia médica"),
	MEDICINA_NUCLEAR("Medicina nuclear"),
	MEDICINA_PREVENTIVA_SOCIAL("Medicina preventiva e social"),
	NEFROLOGIA("Nefrologia"),
	NEUROCIRURGIA("Neurocirurgia"),
	NEUROLOGIA("Neurologia"),
	NUTROLOGIA("Nutrologia"),
	OFTALMOLOGIA("Oftalmologia"),
	ONCOLOGIA_CLINICA("Oncologia clínica"),
	ORTOPEDIA_TRAUMATOLOGIA("Ortopedia e traumatologia"),
	OTORRINOLARINGOLOGIA("Otorrinolaringologia"),
	PATOLOGIA("Patologia"),
	PATOLOGIA_CLINICA_MEDICINA_LABORATORIAL("Patologia clínica/medicina laboratorial"),
	PEDIATRIA("Pediatria"),
	PNEUMOLOGIA("Pneumologia"),
	PSIQUIATRIA	("Psiquiatria"),
	RADIOLOGIA_DIAGNSTICO_IMAGEM("Radiologia e diagnóstico por imagem"),
	RADIOTERAPIA("Radioterapia"),
	REUMATOLOGIA("Reumatologia"),
	UROLOGIA("Urologia"),
	MEC_OPE("Mecânico Operador"),
	MNT_ARM("Manutenção de Armamento"),
	MNT_VTR_AUTO("Manutenção de Viatura Automóvel"),
	MNT_VTR_BL("Manutenção de Viatura Blindada"),
	MNT_COM("Manutenção de Comunicações"),
	C_EXAT_TERRA("Ciências Exatas e da Terra"),
	C_BIO("Ciências Biológicas"),
	ENG("Engenharias"),
	C_SAU("Ciências da Saúde"),
	C_AGRA("Ciências Agrárias"),
	C_HUM("Ciências Humanas"),
	LING_LETR_ART("Linguística, Letras e Artes"),
	C_SOC_APL("Ciências Sociais Aplicadas"),
	GRAD_QEM("Graduação QEM (Formação AMAN)"),
	GRAD_EE_SUP("QEM (Graduação EE Superior)"),
	QEM("Quadro de Engenheiros Militares"),
	ESTAG_CAPEL_MIL("Estágio para Capelães Militares (SAREX)");
	
	
	
	private String descricao;
	
	EspecialidadeArma(String descricao) {
		this.descricao = descricao;
	}

	public String getDescricao() {
		return descricao;
	}
}
